# Generated by Django 3.0.6 on 2020-05-16 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('destination', models.CharField(max_length=50)),
                ('outcome_type', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=0)),
                ('tag', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('origin', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('tag', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
    ]
