# Generated by Django 3.0.6 on 2020-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('r', 'realism'), ('l', 'love'), ('s', 'science')], default='r', max_length=20)),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
